=== Ricardo19F/Guia32G5/Ejercicios/dtd_exterma/ejercicio-ii-2c-dtd-externa.dtd
<!ELEMENT fichero (ficha+, a)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
		<!ELEMENT a (#PCDATA)>
		<!ATTLIST a  
  		href CDATA #IMPLIED
  		xmlns CDATA #IMPLIED 
  		target (_blank|_self|marco) "_blank">
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
    <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>

=== Ricardo19F/Guia32G5/Ejercicios/dtd_exterma/ejercicio-ii-2c-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fichero SYSTEM "ejercicio-ii-2c-dtd-externa.dtd">
<?xml-stylesheet type="text/css" href="estilo-ii-2c.css"?>
<!-- ejercicio-ii-1c-dtd.xml  GRUPO05-->
<fichero>
  <ficha>
    <nombre sexo="femenino" edad="17">Angelina</nombre>
    <apellido>Fernandez</apellido>
    <direccion>c/Ulises, 36</direccion>
  </ficha>
  <!-- Ficha creada por AD17006-->
  <ficha>
    <nombre sexo="masculino">Cristian Rodolfo</nombre>
    <apellido>Alvarez Dominguez</apellido>
    <direccion>Direccion desconocida</direccion>
    <DUI>11111111-1</DUI>
  </ficha>
  <a xmlns="http://www.w3.org/1999/xhtml" href="./../../index.html">Regresar</a>
</fichero>
